apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: pip-gw
  namespace: pip-ns
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 9001
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: pip-vs
  namespace: pip-ns
spec:
  hosts:
    - "pip.com"
  gateways:
    - pip-gw
  http:
    - match:
        - uri:
            prefix: "/api/"
      rewrite:
        uri: "/"
      route:
        - destination:
            host: pip-svc
            port:
              number: 3030
          weight: 100
---
