apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: iot-gw
  namespace: iot-ns
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 30588
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: sys-vs
  namespace: iot-ns
spec:
  hosts:
    - "iot.com"
  gateways:
    - iot-gw
  http:
    - match:
        - uri:
            prefix: "/sys-app/"
      rewrite:
        uri: "/"
      route:
        - destination:
            host: sys-svc
            port:
              number: 9100
          weight: 100
    - match:
        - uri:
            prefix: "/iot-app/"
      rewrite:
        uri: "/"
      route:
        - destination:
            host: iot-svc
            port:
              number: 9200
          weight: 100
    - match:
        - uri:
            prefix: "/notify-app/"
      rewrite:
        uri: "/"
      route:
        - destination:
            host: notify-svc
            port:
              number: 9300
          weight: 100
    - match:
        - uri:
            prefix: "/register-app/"
      rewrite:
        uri: "/"
      route:
        - destination:
            host: register-svc
            port:
              number: 9400
          weight: 100
    - match:
        - uri:
            prefix: "/user-app/"
      rewrite:
        uri: "/"
      route:
        - destination:
            host: user-svc
            port:
              number: 9500
          weight: 100
---
